# platform = multi_platform_konvoy
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- name: "@RULE_TITLE@"
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_AUTO_TLS='
    line: "ETCD_AUTO_TLS=true"
    create: yes
