# platform = multi_platform_konvoy
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: "@RULE_TITLE@"
  lineinfile:
    path: /etc/etcd/etcd.conf
    regexp: '^ETCD_PEER_KEY_FILE'
    line: "ETCD_PEER_KEY_FILE=/etc/kubernetes/pki/etcd/peer.key"
    create: yes
