product: konvoy5
full_name: Konvoy 5
type: platform

benchmark_root: "../applications"

additional_content_directories:
    - "../linux_os/guide/services"
    - "../linux_os/guide/system/auditing"
    - "../linux_os/guide/system/selinux"
    - "../linux_os/guide/system/software"
    - "../linux_os/guide/system/accounts"
    - "../linux_os/guide/system/permissions"
    - "../linux_os/guide/system/logging"
    - "../linux_os/guide/system/bootloader-grub2"
    - "../linux_os/guide/system/network"

profiles_root: "./profiles"

pkg_system: "rpm"

init_system: "systemd"

# Requirement string, see: https://setuptools.readthedocs.io/en/latest/pkg_resources.html#requirements-parsing
# requires: "openscap>=1.3.3"
